modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="airport_security"
version="1.0.0"
displayName="Airport Security"
authors="ZareMate"
description='''Server-side client verification for NeoForge.'''

[[mixins]]
config="keycheck.mixins.json"
